Add Checksum to Image Display
mwarning/yet-another-firmware-selector pull request #63
Opened 2020-10-22 18:17 UTC by mwarning

Show the hash/checksum beneath the image download link when the mouse hovers of the download link.

2020-10-22 18:17 UTC, mwarning commented
@aparcar what do you think? Should we use "Checksum:", "Hash:" or even "SHA256:"?

2020-10-23 19:55 UTC, aparcar commented
Hi, can you please add a screenshot? Also it would be great if you could propose this to the OpenWrt repository [here](https://gitlab.com/openwrt/web/firmware-selector-openwrt-org)

2020-10-23 19:58 UTC, aparcar commented
I'd call it `sha256sum` which is the same as on downloads.openwrt.org. It both describes the used Algorithm and also is language independent, so we don't need to add it to the translations as all.

2020-10-23 20:01 UTC, aparcar requested changes

2020-10-23 20:01 UTC, aparcar commented on www/index.html
> +              <span id="image-hash"></span>
```suggestion
              <span id="image-sha256"></span>
```

2020-10-23 20:01 UTC, aparcar commented on www/index.js
> +    setValue("#image-hash", undefined);
```suggestion
    setValue("#image-sha256", undefined);
```

2020-10-23 20:01 UTC, aparcar commented on www/index.js
> +        setValue("#image-hash", image.hash);
```suggestion
        setValue("#image-sha256", image.sha256);
```

2020-10-23 20:01 UTC, aparcar commented
This is not a big thing but I'd rather keep the checksum variables descriptive, imagine we want to use sha3  or whatever else at some point...

2020-10-24 10:12 UTC, mwarning commented on www/index.html
> +              <span class="column tr-hash">Hash:</span>
We need to keep `class="column"` to apply CSS formatting.

2020-10-24 10:23 UTC, aparcar commented on www/index.html
> +              <span class="column tr-hash">Hash:</span>
Oh oops!

2020-10-24 11:00 UTC, mwarning commented
"sha256sum:" as label is a good idea.

2020-10-25 21:35 UTC, aparcar commented
Thanks for the rework. Could you please create a PR [here](https://gitlab.com/openwrt/web/firmware-selector-openwrt-org/-/merge_requests) and to keep this repository in sync?

2020-10-25 21:48 UTC, mwarning commented
@aparcar I haven't merged this because I am not quite happy about this:
- the design does look a bit odd, maybe it is just me
- the hash blows up the overview.png without being able to remove easily them

![file](https://user-images.githubusercontent.com/546193/97119964-1855e800-1714-11eb-8908-388a9fe9aac6.png)

2020-10-25 21:51 UTC, aparcar commented
What about reducing the font size of the hash? (Like in the patch i send you last week)

2020-10-25 21:59 UTC, mwarning commented
Looks better that way:
![file](https://user-images.githubusercontent.com/546193/97120199-b4ccba00-1715-11eb-8e67-b08d46fa284c.png)

2020-11-13 22:11 UTC, mwarning commented
done

2020-11-13 22:11 UTC, closed without merging